---
title: "12_AssociationAnalysis"
author: "Nikhil Gupta"
date: "July 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Potential Installation issues
# https://stackoverflow.com/questions/18023300/is-rgraphviz-no-longer-available-for-r
# source("http://bioconductor.org/biocLite.R")
# biocLite("Rgraphviz") # replace the library name with the one that is missing

require("pacman")
pacman::p_load(mlbench,arules,arulesViz)
```


```{r}
data(Zoo) # load up an R DataFrame
head(Zoo) # print part of it from R
```

# Using R with apriori

```{r}
# load up some zoo data
data(Zoo)
```


```{r}
# make the "legs" attirbute binary
has_legs <- Zoo["legs"]>0
Zoo[["legs"]] <- as.factor(has_legs)
str(Zoo)
```

## Convert Dataframe to Transactions
```{r}
# convert to transactions, where column indicates the output of the attribute
# so "hair" as an attribute would generate two columns -> "hair=TRUE and hair=FALSE"

# basically converting the dataframe into a new class objecr of type "transactions". This type is defined in the arules library
trans <- as(Zoo, "transactions")
str(trans)
```



```{r}
# What does trans contain?
trans@itemInfo # Columns (one hot encoded)
head(trans@itemsetInfo) # Observation labels
```

## Frequent Itemsets
**Get the Frequent Itemsets using Apriori algorithm**

```{r}
# Now that we have transactions, its time to run the apriori algorithm

# apriori --> This mines and returns the frequent itemsets, association rules or association hyperedges using the Apriori algorithm

# (1) parameter: object of class APparameter or named list. The default behavior is to mine rules with minimum support of 0.1, minimum confidence of 0.8, maximum of 10 items (maxlen), and a maximal time for subset checking of 5 seconds (maxtime).
# (2) target="frequent" gets the frequent itemsets
isets <- apriori(trans, parameter=list(target="frequent", support=0.5))
```

```{r}
# Basic information in isets
isets # there are 21 item sets
isets@quality # This lists the support for each item set
```

```{r}
# sort it and display some of the frequent itemsets from apriori
isets <- arules::sort(isets, by="support")  # Note this is not base sort, it is a sort function in the library arules
inspect(head(isets, n=10))
length(isets)
```

```{r}
# Do same thing, getting only the maximal sets
is_max <- isets[is.maximal(isets)]
inspect(head(arules::sort(is_max, by="support")))
length(is_max)
```

## Association Rules

```{r}
# generate some rules from the frequent itemsets
rules <- apriori(trans, parameter=list(support=.5, confidence=.9))

head(rules, n=10) # just states that there are 10 rules (use inspect to see rules)
inspect(head(rules, n=10)) # inspect is an arules function to display rules in readable format
```

```{r}
# print out measures of rule quality (also available from the inspect function above)
quality(head(rules))
```


```{r}
# sort out the rules and print additional "interest" measures
rules <- sort(rules, by="lift")
inspect(head(rules, n=10))
```

```{r}
interestMeasure(rules[1:10], measure=c("phi", "gini"), trans=trans)
```

## Visualizing the Results


```{r}
plot(rules) # uses plot function from arules library
```

```{r fig.height=12, fig.width=10}
# a great plot
plot(rules, method="grouped")
inspect(rules)
length(rules)
```

## Extended Example (Titanic Dataset)
**http://www.rdatamining.com/examples/association-rules** 

```{r fig.height=12, fig.width=10}

load("ICA5/ICA5-PartA/titanic2.raw.rdata")
rules <- apriori(titanic.raw,parameter = list(minlen=2, supp=0.005, conf=0.8), appearance = list(rhs=c("Survived=No", "Survived=Yes"), default="lhs"), control = list(verbose=F))
rules.sorted <- sort(rules, by="lift")
plot(rules.sorted, method="grouped")
inspect(rules.sorted, n=10)
```